### ISSUE TITLE
Crash on parse...

### ISSUE THREAD

**Issue by arcataroger** [stekhn/location-history#1]
Hmm,

Not sure if this is still maintained, but I get the following error trying to parse a large (500 MB) file:

```
buffer.js:495
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at Object.parse (native)
    at handleFile (C:\Users\user_\Downloads\location-history-master\convert.js:38:25)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
```

**Comment by stekhn** [comment]
For big files, the synchronous Node.js method `fs.readFile()` does not work well. The application code should be updated to use `fs.createReadStream()` instead. There is a good [Stackoverflow article](https://stackoverflow.com/questions/11874096/parse-large-json-file-in-nodejs) explaining how to do that.

If the problem is memory related, there is an easy way to temporarily increase the memory allocated by Node.js:

```
$ node --max-old-space-size=8192 convert.js  
``` 

If you would like to update the project using streams, I'd gladly accept a pull request.
